bittle:
  effort_controller:
    type: "effort_controllers/JointGroupPositionController"
    publish_rate: 50
    joints:
      - left_back_knee_joint
      - left_back_shoulder_joint
      - left_front_knee_joint
      - left_front_shoulder_joint
      - right_back_knee_joint
      - right_back_shoulder_joint
      - right_front_knee_joint
      - right_front_shoulder_joint
    left_back_knee_joint:
      pid: {p: 5, i: 3, d: 0.9}
    left_back_shoulder_joint:
      pid: {p: 5, i: 3, d: 0.9}
    left_front_knee_joint:
      pid: {p: 5, i: 3, d: 0.9}
    left_front_shoulder_joint:
      pid: {p: 5, i: 3, d: 0.9}
    right_back_knee_joint:
      pid: {p: 5, i: 3, d: 0.9}
    right_back_shoulder_joint:
      pid: {p: 5, i: 3, d: 0.9}
    right_front_knee_joint:
      pid: {p: 5, i: 3, d: 0.9}
    right_front_shoulder_joint:
      pid: {p: 5, i: 3, d: 0.9}
